## The Rank of a matrix

# Library Load

In [1]:
import numpy as np

# Q1.
You are a lead engineer at **Stark Industries** working on robotics special projects. You stumble upon the old schematics of the Iron Man suit and decide to take on an ambitious project. As a savvy engineer, you realize the potential of upgrading the exoskeleton to help people walk after a neurological injury.
  
To ensure your exoskeleton is affordable and slim, you generate a new composite structure combining fiberglass, aluminum, and carbon nanotube materials. Ultimately, you need to assess the price of each material. 
  
**1st iteration:** You use 7 units of fiberglass, 5 units of aluminum, and 3 units of carbon nanotubes, which cost $120.
  
**2nd iteration:** You engineer a less wasteful process that uses 3 units of fiberglass, 2 units of aluminum, and 5 units of carbon nanotubes to produce the same amount of composite, the total cost is $70.
  
**3rd iteration:** You combine electrostimulation delivery, which cuts down the cost of the suit by using only 1 unit of fiberglass, 2 units of aluminum, and 1 unit of carbon nanotubes, which cost $20. 
  
**Which of the following represents the correct system of equations?**

# A1. 
$\begin{cases}
    7f + 5a + 3c = 120 \\
    3f + 2a + 5c = 70 \\
    f + 2a + c = 20
\end{cases}$

> Each equation should represent one iteration - E1 (the first equation) shows the units used in the first iteration for fiberglass (7), aluminum (5) and carbon nanotubes (3) which all cost $120. The same process is applied to the two other equations.

In [2]:
A = np.array([
    [7, 5, 3],
    [3, 2, 5],
    [1, 2, 1]
], dtype=np.dtype(float))

b = np.array(
   [120, 70, 20]
, dtype=np.dtype(float))

# Q2.
**Which of the following steps can you take to solve the system of equations? Select all that apply.**

# A2.
Isolate one variable and substitute into the next equation to find the other variable.  
> This is also known as the method of substitution, where you isolate one variable $(either f, a,$ or $c)$ and substitute its value into the other equation to find the remaining variable. 

Divide the first equation by 7.
> This is one of the first steps you can take to create an entry of 1 and start simplifying the system of equations, or matrix (into REF or RREF form). 

Subtract the second row from the first row.
> This is one way of finding the solutions for the values of $f, a$ and $c$.

Multiply the first equation by 3 and subtract it from equation 2.

Multiply by a scalar and add the two rows. 
> Which number can you use to multiply the second equation to subtract from the first one?

In [3]:
A_system = np.hstack((A, b.reshape(3, 1)))
A_system

array([[  7.,   5.,   3., 120.],
       [  3.,   2.,   5.,  70.],
       [  1.,   2.,   1.,  20.]])

In [4]:
# Divide the first equation by 7.
A_system[0] / 7

array([ 1.        ,  0.71428571,  0.42857143, 17.14285714])

In [5]:
# Subtract the second row from the first row.
A_system[1] - A_system[0]

array([ -4.,  -3.,   2., -50.])

In [6]:
# Multiply the first equation by 3 and subtract it from equation 2.
A_system[1] - A_system[0] * 3

array([ -18.,  -13.,   -4., -290.])

# Q3.
**Which of the following information can you extract from the given system of equations?**

# A3.
Row-reduced echelon form.
> RREF or row-reduced echelon form is the simplest reduction method to a matrix that in its simplest form has 1s diagonally, and 0s elsewhere. If you’re curious, bring the current matrix of the problem into RREF form

The rank of the matrix.
> You can determine the rank from the number of independent rows in the matrix. What other ways can you use to find the rank? Think back from system of sentences video.

The cost of each material.
>  Your ultimate goal is to determine the cost of material from solving the system of linear equations or the matrix representation of it.

Whether the matrix is singular or non-singular.
> There are a few ways to distinguish between a singular vs non-singular matrix. You can determine this by finding the determinant. 

Number of linearly (in)dependent rows and columns.
> How many new pieces of information you get from the system of linear equations? When you can obtain new pieces of information, the system has linearly independent rows. Else, if you can obtain one row from operating on the others, then the rows are linearly dependent. 

# Q4.
**Which of the following matrices represents the system of sentences in Q1 for all three iterations?**

# A4.
$\begin{bmatrix}
7 & 5 & 3 \\
3 & 2 & 5 \\
1 & 2 & 1
\end{bmatrix}$
> As you learned in the video "System of equations", a system of sentences can be translated into a system of equations and this in it can be translated into a matrix. 

# Q5.
**Calculate the cost of each material by solving the system of equations.**  
Hint: You can use the method of substitution, or row reducing the matrix to a simpler form. 

# A5. 
fiberglass = $15, aluminum = $0, carbon nanotubes = $5
> It turns out you didn't spend anything on aluminum, since it was most likely provided by the Stark Corporation! 

In [7]:
A_system

array([[  7.,   5.,   3., 120.],
       [  3.,   2.,   5.,  70.],
       [  1.,   2.,   1.,  20.]])

In [8]:
np.linalg.solve(A, b)

array([1.50000000e+01, 8.63506797e-16, 5.00000000e+00])

In [9]:
def augmented_to_ref(A, b):
    A_system = np.hstack((A, b.reshape(3, 1)))
    A_system[[2, 0]] = A_system[[0, 2]]
    A_ref = A_system.copy()
    A_ref[1] = A_ref[0] * -3 + A_ref[1]
    A_ref[0] = A_ref[1] + A_ref[0]
    A_ref[2] = A_ref[0] * -7 + A_ref[2]
    A_ref[2] = A_ref[1] * 5 + A_ref[2]
    A_ref[1] = A_ref[2] * -5 + A_ref[1]
    A_ref[2] = A_ref[1] + A_ref[2]
    A_ref[2] = A_ref[2] * 1/34
    return A_ref

A_ref = augmented_to_ref(A, b)

print(A_ref)

[[  1.  -2.   3.  30.]
 [  0.   1.  42. 210.]
 [  0.   0.   1.   5.]]


In [10]:
c = A_ref[2][3]
a = A_ref[1][3] - A_ref[1][2] * c
f = A_ref[0][3] - A_ref[0][2] * c - A_ref[0][1] * a

print(f, a, c)

15.0 0.0 5.0


# Q6.
**Use the determinant to find if the matrix is singular or non-singular. Is the matrix in Row-echelon form or Reduced row-echelon form?**

# A6.
-34, Non-singular, Neither
> The determinant for the 3x3 matrix is -34. By definition, a matrix with determinant 0 is singular, while any other value is non-singular. Therefore, the matrix provided is non-singular. 

In [11]:
np.linalg.det(A)

-34.00000000000001

# Q7.
**What is the rank in the above matrix?**

# A7.
3
> You have three iterations where you find the cost of each of the three materials used. Therefore, the rank of the matrix is 3 since there are 3 linearly independent rows in it.

# Q8.
To assist you with your design choices, your AI assistant compiles a few matrices with different combinations of materials. Since your experiments are not free, you want to try the option that gives you the highest amount of information.  
  
Sort the matrices from the one that provides the lowest amount of information to the highest ( from the lowest rank to the highest rank). 

a. 
$\begin{bmatrix}
0 & 1 & 1 \\
2 & 4 & 2 \\
1 & 2 & 1
\end{bmatrix}$

b.
$\begin{bmatrix}
7.5 & 5 & 12.5 \\
3 & 2 & 5 \\
0 & 0 & 0
\end{bmatrix}$

c.
$\begin{bmatrix}
7 & 5 & 3 \\
3 & 2 & 5 \\
1 & 2 & 1
\end{bmatrix}$

Hint: To help you get started, determine which matrices have linearly dependent rows. You've already found the rank of the third matrix!

# A8.
b, a, c
> Matrices b, a, and c represent the rank ordered from lowest (1) to the highest (3).

# Q9.
**To further optimize the cost of materials, you finally reduce your number of iterations to only 2 tries, where you now obtain a 2x2 matrix with rank 1.**
  
**Which of the following is your matrix?**
  
Hint: Which of the following 2x2 matrices have rank  = 1?

# A9.
$\begin{bmatrix}
1 & 1 \\
2 & 2 
\end{bmatrix}$
> The solution for the matrix consists of a line in the graph. This means that the rank is equal to 1.